### ISSUE TITLE
Widescope

### ISSUE THREAD

**Issue by wyfsmn** [RazvanDu/DUCK-Net#12]
Widescope simulates a kernel size of 15 × 15，you use dilation_rate=1,2,3,How does it simulate 15 * 15 ? Isn't it 13 * 13

**Comment by RazvanDu** [comment]
Hello,

That is indeed a typo in our paper, it should be 3+4+6=13.

It's too late for us to fix it now, but thanks for pointing it out and sorry for the issue.
