### ISSUE TITLE
Hi, I have a problem I can't solve

### ISSUE THREAD

**Issue by Xwei-nobug** [RazvanDu/DUCK-Net#13]
![屏幕截图 2024-01-22 134306](https://github.com/RazvanDu/DUCK-Net/assets/154236063/fc3f3704-88cf-4614-a9de-dd4f6f5208bf)
It shows that there is a utf-8 encoding problem, but I do not know how to solve it.I haven't changed the program, Sir. Do you have a good solution？

**Comment by maenstru56** [comment]
Hello,

I think the most likely explanation for the error is the way the save paths are defined. Based on your operating system you might want to modify these lines of code:
ct = datetime.now()

model_type = "DuckNet"

progress_path = 'ProgressFull/' + dataset\_type + '\_progress\_csv\_' + model\_type + '\_filters\_' + str(filters) +  '\_' + str(ct) + '.csv'
progressfull_path = 'ProgressFull/' + dataset\_type + '\_progress\_' + model\_type + '\_filters\_' + str(filters) + '\_' + str(ct) + '.txt'
plot_path = 'ProgressFull/' + dataset\_type + '\_progress\_plot\_' + model\_type + '\_filters\_' + str(filters) + '\_' + str(ct) + '.png'
model_path = 'ModelSaveTensorFlow/' + dataset\_type + '/' + model\_type + '\_filters\_' + str(filters) + '\_' + str(ct)

I suggest that you try experimenting with the following:
- First, try replacing the character ":" from the datetime with a "\_", as in some cases this may be problematic. I suggest the following modification:
progress_path = './ProgressFull/' + dataset\_type + '\_progress\_csv\_' + model\_type + '\_filters\_' + str(filters) +  '\_' + str(ct).replace(':', '\_') + '.csv'
progressfull_path = './ProgressFull/' + dataset\_type + '\_progress\_' + model\_type + '\_filters\_' + str(filters) + '\_' + str(ct).replace(':', '\_') + '.txt'
plot_path = './ProgressFull/' + dataset\_type + '\_progress\_plot\_' + model\_type + '\_filters\_' + str(filters) + '\_' + str(ct).replace(':', '\_') + '.png'
model_path = './ModelSaveTensorFlow/' + dataset\_type + '/' + model\_type + '\_filters\_' + str(filters) + '\_' + str(ct).replace(':', '\_')

- If the above solution doesn't work, try to change "\/" into "\\" or "\\\\", as some operating systems prefer the latter
- Finally, if nothing else seem to work, use the "os" python library for handling the paths, you can find some online documentation on how to use it here: https://docs.python.org/3/library/os.html

I hope this helps!

**Comment by Xwei-nobug** [comment]
Thank you Sir, modification according to your method can run perfectly on Windows 11, it is very helpful for beginners like me, thank you again!
