### ISSUE TITLE
Pytorch implementation

### ISSUE THREAD

**Issue by long-nguyen12** [RazvanDu/DUCK-Net#14]
Thanks for your interesting research. Do you have any plan to implement this research in Pytorch?

**Comment by RazvanDu** [comment]
Thanks!

Unfortunately, we don't have any current plans of porting the architecture, but we are open to support anyone that is interested in doing it.

**Comment by long-nguyen12** [comment]
Thanks for your reply! I'm trying to re-implement in Pytorch. If you have free time, plz take a look at [link](https://github.com/long-nguyen12/DUCK-Net-Pytorch). My testing results are not the same as yours

**Comment by RazvanDu** [comment]
Are you using the exact same data split that we are using in our project?

**Comment by long-nguyen12** [comment]
> Are you using the exact same data split that we are using in our project?

Yes, we use exactly you data split but the results are not good.
