### ISSUE TITLE
library dependency

### ISSUE THREAD

**Issue by derejere** [RazvanDu/DUCK-Net#2]
I think there is a small error in the "requirements.txt" file containing the necessary libraries. The module tensorflow = 2.9.1 depends on keras<2.10, but keras=2.10 is specified in the file. Sorry if I overlooked something, I am quite new to this.

**Comment by RazvanDu** [comment]
Hey, sorry for the issue, it was a mistake on our part because we had two versions of TensorFlow installed simultaneously. We've updated the "requirements.txt" file with the correct Tensorflow version. Thanks for the feedback!

**Comment by derejere** [comment]
Alright thank you!
