### ISSUE TITLE
Unable to Access Test Dataset

### ISSUE THREAD

**Issue by seekerhuang** [RazvanDu/DUCK-Net#7]
Hi,

I hope this message finds you well. I am currently facing an issue with accessing the test dataset provided. It seems that the test dataset is no longer accessible. Could you please provide it again?

Thank you very much for your assistance.

**Comment by maenstru56** [comment]
Hello,

The initial google drive links with the data had editing privileges and for some reason people kept deleting the files. Now I uploaded them again and updated the privileges so they can't be deleted anymore, you should be able to download them.

Thanks for pointing out the issue and I hope this helps!
